Workaround to prevent following error:

[...]
  File "/usr/local/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 58, in validate
    return validate_pep621(self.data, raising)
  File "/usr/local/lib/python3.9/site-packages/pdm/pep517/validator.py", line 85, in validate_pep621
    raise PEP621ValidationError(validator.errors)
pdm.pep517.exceptions.PEP621ValidationError: {'license-expression': ['unknown field']}

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
*** Error code 1
[...]

--- pyproject.toml.orig	2022-05-28 13:34:29 UTC
+++ pyproject.toml
@@ -10,7 +10,6 @@ authors = [
 authors = [
     { name = "TimothÃ©e Mazzucotelli", email = "pawamoy@pm.me" },
 ]
-license-expression = "ISC"
 readme = "README.md"
 requires-python = ">=3.7"
 keywords = []
